# Generated by Django 4.1.2 on 2022-10-14 21:06

import django.db.models.deletion
import wagtail.fields as wagtail_fields

from django.db import migrations, models

import wagtail_footnotes.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0040_page_draft_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPageStreamField",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail_fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail_footnotes.blocks.RichTextBlockWithFootnotes(
                                    features=["footnotes"]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
