# Generated by Django 6.1.1 on 2026-10-01 10:26

import wagtail.fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpagestreamfield",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("caption_richtext_filter", 1),
                    ("caption_include_block", 1),
                ],
                block_lookup={
                    0: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {"features": ["footnotes"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("caption", 0)]], {}),
                },
            ),
        ),
    ]
