# Generated by Django 3.2.4 on 2021-06-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtail_footnotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="footnote",
            unique_together={("page", "uuid")},
        ),
    ]
