# Generated by Django 3.2.4 on 2021-06-24 10:18

from django.db import migrations

import wagtail_footnotes.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("wagtail_footnotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="footnote",
            unique_together={("page", "uuid")},
        ),
        migrations.AlterField(
            model_name="footnote",
            name="uuid",
            field=wagtail_footnotes.fields.CustomUUIDField(
                help_text="The ID of the footnote is shown in the rich text editor for reference.",
                verbose_name="ID",
            ),
        ),
    ]
