# Generated by Django 4.1.9 on 2023-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_footnotes", "0002_alter_footnote_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
