# Generated by Django 4.2.9 on 2024-01-11 12:53

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("wagtail_footnotes", "0002_alter_footnote_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="footnote",
            unique_together={("page", "uuid")},
        ),
        migrations.AddField(
            model_name="footnote",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="footnote",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="footnote",
            unique_together={("translation_key", "locale"), ("page", "uuid")},
        ),
    ]
