# Generated by Django 4.2.9 on 2024-01-11 12:56

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_footnotes", "0003_add_bootstrap_translatable_mixin"),
    ]

    operations = [
        BootstrapTranslatableModel("wagtail_footnotes.Footnote"),
    ]
