# Generated by Django 4.2.15 on 2024-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_footnotes", "0006_alter_footnote_locale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnote",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="footnote",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
