name: Publish to PyPI

on:
  release:
    types: [released, prereleased]

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  PYTHON_LATEST: "3.11"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_LATEST}}

      - name: Install dependencies
        run: |
          python -Im pip install --upgrade pip
          python -Im pip install wheel
      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: '__token__'
          password: ${{ secrets.PYPI_API_TOKEN }}
